# Generated by Django 5.1.2 on 2024-10-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_image',
            new_name='product_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CZ', 'Cheese'), ('ML', 'Milk'), ('CR', 'Curd'), ('IC', 'Ice-cream'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('LS', 'Lassi'), ('GH', 'Ghee')], max_length=2),
        ),
    ]
