# Generated by Django 5.1.2 on 2024-10-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_category_customer_delete_customeer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Gujarat', 'Gujarat'), ('Ladakh', 'Ladakh'), ('Odisha', 'Odisha'), ('Goa', 'Goa'), ('West Bengal', 'West Bengal'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Assam', 'Assam'), ('Maharashtra', 'Maharashtra'), ('Rajasthan', 'Rajasthan'), ('Chandigarh', 'Chandigarh'), ('Uttarakhand', 'Uttarakhand'), ('Tamil Nadu', 'Tamil Nadu'), ('Mizoram', 'Mizoram'), ('Tripura', 'Tripura'), ('Jharkhand', 'Jharkhand'), ('Sikkim', 'Sikkim'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Telangana', 'Telangana'), ('Manipur', 'Manipur'), ('Nagaland', 'Nagaland'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Lakshadweep', 'Lakshadweep'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Delhi', 'Delhi'), ('Haryana', 'Haryana'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Kerala', 'Kerala'), ('Chhattisgarh', 'Chhattisgarh'), ('Meghalaya', 'Meghalaya'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Bihar', 'Bihar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Karnataka', 'Karnataka')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Milk'), ('GH', 'Ghee'), ('MS', 'Milkshake'), ('LS', 'Lassi'), ('CR', 'Curd'), ('IC', 'Ice-cream'), ('PN', 'Paneer'), ('CZ', 'Cheese')], max_length=2),
        ),
    ]
