# Generated by Django 5.1.2 on 2024-10-24 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customer_state_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Karnataka', 'Karnataka'), ('Tripura', 'Tripura'), ('Ladakh', 'Ladakh'), ('Mizoram', 'Mizoram'), ('Telangana', 'Telangana'), ('Kerala', 'Kerala'), ('Haryana', 'Haryana'), ('Assam', 'Assam'), ('Tamil Nadu', 'Tamil Nadu'), ('Punjab', 'Punjab'), ('Sikkim', 'Sikkim'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Bihar', 'Bihar'), ('Maharashtra', 'Maharashtra'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Lakshadweep', 'Lakshadweep'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Nagaland', 'Nagaland'), ('Gujarat', 'Gujarat'), ('West Bengal', 'West Bengal'), ('Delhi', 'Delhi'), ('Chandigarh', 'Chandigarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Rajasthan', 'Rajasthan'), ('Manipur', 'Manipur'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Meghalaya', 'Meghalaya'), ('Odisha', 'Odisha'), ('Uttarakhand', 'Uttarakhand'), ('Chhattisgarh', 'Chhattisgarh'), ('Puducherry', 'Puducherry'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Goa', 'Goa'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PN', 'Paneer'), ('CR', 'Curd'), ('MS', 'Milkshake'), ('IC', 'Ice-cream'), ('LS', 'Lassi'), ('CZ', 'Cheese'), ('ML', 'Milk'), ('GH', 'Ghee')], max_length=2),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
