# Generated by Django 5.1.2 on 2024-10-27 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customer_state_alter_product_category_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Mizoram', 'Mizoram'), ('Lakshadweep', 'Lakshadweep'), ('Ladakh', 'Ladakh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Nagaland', 'Nagaland'), ('Assam', 'Assam'), ('Manipur', 'Manipur'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Chhattisgarh', 'Chhattisgarh'), ('Tamil Nadu', 'Tamil Nadu'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Kerala', 'Kerala'), ('West Bengal', 'West Bengal'), ('Uttarakhand', 'Uttarakhand'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Punjab', 'Punjab'), ('Haryana', 'Haryana'), ('Puducherry', 'Puducherry'), ('Bihar', 'Bihar'), ('Odisha', 'Odisha'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Rajasthan', 'Rajasthan'), ('Chandigarh', 'Chandigarh'), ('Maharashtra', 'Maharashtra'), ('Karnataka', 'Karnataka'), ('Goa', 'Goa'), ('Meghalaya', 'Meghalaya'), ('Jharkhand', 'Jharkhand'), ('Gujarat', 'Gujarat'), ('Delhi', 'Delhi'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Sikkim', 'Sikkim')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('ML', 'Milk'), ('CZ', 'Cheese'), ('IC', 'Ice-cream')], max_length=2),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancell', 'Cancell'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.payment')),
            ],
        ),
    ]
