# Generated by Django 5.1.2 on 2024-10-30 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customer_state_alter_product_category_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Gujarat', 'Gujarat'), ('Manipur', 'Manipur'), ('Haryana', 'Haryana'), ('Goa', 'Goa'), ('Nagaland', 'Nagaland'), ('Chhattisgarh', 'Chhattisgarh'), ('Lakshadweep', 'Lakshadweep'), ('Jharkhand', 'Jharkhand'), ('Odisha', 'Odisha'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Assam', 'Assam'), ('Telangana', 'Telangana'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Rajasthan', 'Rajasthan'), ('Bihar', 'Bihar'), ('Tripura', 'Tripura'), ('West Bengal', 'West Bengal'), ('Puducherry', 'Puducherry'), ('Sikkim', 'Sikkim'), ('Chandigarh', 'Chandigarh'), ('Maharashtra', 'Maharashtra'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Meghalaya', 'Meghalaya'), ('Delhi', 'Delhi'), ('Kerala', 'Kerala'), ('Mizoram', 'Mizoram'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Tamil Nadu', 'Tamil Nadu'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Karnataka', 'Karnataka'), ('Ladakh', 'Ladakh'), ('Punjab', 'Punjab'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Uttarakhand', 'Uttarakhand')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PN', 'Paneer'), ('IC', 'Ice-cream'), ('GH', 'Ghee'), ('ML', 'Milk'), ('CR', 'Curd'), ('CZ', 'Cheese'), ('LS', 'Lassi'), ('MS', 'Milkshake')], max_length=2),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
