# Generated by Django 5.1.2 on 2024-11-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_customer_state_alter_product_category_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Assam', 'Assam'), ('Haryana', 'Haryana'), ('West Bengal', 'West Bengal'), ('Delhi', 'Delhi'), ('Chandigarh', 'Chandigarh'), ('Bihar', 'Bihar'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Rajasthan', 'Rajasthan'), ('Gujarat', 'Gujarat'), ('Ladakh', 'Ladakh'), ('Telangana', 'Telangana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Mizoram', 'Mizoram'), ('Lakshadweep', 'Lakshadweep'), ('Manipur', 'Manipur'), ('Jharkhand', 'Jharkhand'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Kerala', 'Kerala'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Uttarakhand', 'Uttarakhand'), ('Tamil Nadu', 'Tamil Nadu'), ('Puducherry', 'Puducherry'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Chhattisgarh', 'Chhattisgarh'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Meghalaya', 'Meghalaya'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Sikkim', 'Sikkim'), ('Karnataka', 'Karnataka'), ('Maharashtra', 'Maharashtra'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Nagaland', 'Nagaland'), ('Tripura', 'Tripura')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CZ', 'Cheese'), ('IC', 'Ice-cream'), ('LS', 'Lassi'), ('ML', 'Milk'), ('PN', 'Paneer'), ('CR', 'Curd'), ('GH', 'Ghee'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
